resources:
  - deployments/auth-svc.yaml
  - deployments/frontend-svc.yaml
  - deployments/postgres.yaml
  - deployments/backend-svc.yaml
  - deployments/postgres-game.yaml
  - deployments/kafka.yaml
  - services/auth-svc.yaml
  - services/frontend-svc.yaml
  - services/postgres-svc.yaml
  - services/backend-svc.yaml
  - services/postgres-game.yaml
  - services/kafka-svc.yaml
  - pvcs/postgres-pvc.yaml
  - pvcs/auth-pvc.yaml
  - pvcs/postgres-game-pvc.yaml
