apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  AUTH_URL: "http://dev.condensation.corentindupaigne.com"
  API_URL: "http://auth-svc"
  REDIRECT_URI: "http://dev.condensation.corentindupaigne.com/api/auth/callback"
  HOSTNAME: "0.0.0.0"
  CLIENT_ID: "ead85488-0ee1-41f9-9703-eac26103f5f4"
  BACKEND_URL: "http://backend-svc:8080"
