apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-cm
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Postgres (dev)",
          "Group": "Servers",
          "Host": "postgres-svc",
          "Port": 5432,
          "MaintenanceDB": "auth_db",
          "Username": "postgres",
          "SSLMode": "prefer"
        }
      }
    }
