apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-cm
data:
  APP_NAME: "laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://condensation.corentindupaigne.com"
  FRONTEND_URL: "https://condensation.corentindupaigne.com"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "error"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  # Update after running: kubectl exec -n prod <auth-pod> -- php artisan passport:client --personal
  CLIENT_ID: "9d08613c-0aea-4168-8643-69e29782d452"
  REDIRECT_URI: "https://condensation.corentindupaigne.com/api/auth/callback"
