apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  AUTH_URL: "https://condensation.corentindupaigne.com"
  API_URL: "http://auth-svc"
  REDIRECT_URI: "https://condensation.corentindupaigne.com/api/auth/callback"
  HOSTNAME: "0.0.0.0"
  # Must match CLIENT_ID in auth-cm (update after passport:client)
  CLIENT_ID: "9d08613c-0aea-4168-8643-69e29782d452"
  BACKEND_URL: "http://backend-svc:8080"
