apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-svc
  name: auth-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-svc
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - image: ghcr.io/corentin-dupaigne/fullstack_project/auth
        name: condensation-auth
        envFrom:
          - configMapRef:
              name: auth-cm
          - secretRef:
              name: auth-secret
        imagePullPolicy: Always
        resources: {}
        volumeMounts:
        - name: auth-storage
          mountPath: /var/www/html/storage
      volumes:
      - name: auth-storage
        persistentVolumeClaim:
          claimName: auth-pvc
status: {}
