apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-svc
  name: backend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-svc
  strategy: {}
  template:
    metadata:
      labels:
        app: backend-svc
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - image: ghcr.io/corentin-dupaigne/fullstack_project/backend
        name: condensation-backend
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: backend-cm
          - secretRef:
              name: backend-secret
        imagePullPolicy: Always
        resources: {}
status: {}
