apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-svc
  name: frontend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-svc
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-svc
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - image: ghcr.io/corentin-dupaigne/fullstack_project/frontend
        env:
          - name: HOSTNAME
            value: "0.0.0.0"
        name: condensation-frontend
        resources: {}
status: {}
