apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: apache/kafka:3.7.0
        name: kafka
        ports:
        - containerPort: 9092
        - containerPort: 9093
        envFrom:
          - configMapRef:
              name: kafka-cm
        resources: {}
status: {}
