apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  strategy: {}
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      containers:
      - image: dpage/pgadmin4
        name: pgadmin
        ports:
        - containerPort: 80
        env:
        - name: SCRIPT_NAME
          value: /pgadmin
        envFrom:
        - secretRef:
            name: pgadmin-secret
        readinessProbe:
          httpGet:
            path: /pgadmin/misc/ping
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        - name: pgadmin-servers
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
        resources: {}
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-pvc
      - name: pgadmin-servers
        configMap:
          name: pgadmin-cm
status: {}
