apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres
        volumeMounts:
        - name: postgres-vol
          mountPath: /var/lib/postgresql
        envFrom:
          - secretRef:
              name: postgres-secret
        name: postgres
        resources: {}
      volumes:
      - name: postgres-vol
        persistentVolumeClaim:
          claimName: postgres-pvc

status: {}
