apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-game
  name: postgres-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-game
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres-game
    spec:
      containers:
      - image: ghcr.io/corentin-dupaigne/fullstack_project/postgres-game
        name: postgres-game
        envFrom:
          - secretRef:
              name: postgres-game-secret
        imagePullPolicy: Always
        volumeMounts:
        - name: postgres-game-vol
          mountPath: /var/lib/postgresql
        resources: {}
      volumes:
      - name: postgres-game-vol
        persistentVolumeClaim:
          claimName: postgres-game-pvc
status: {}
