import json
import random
import re
import string
import sys
import time
import urllib.request
import urllib.error
from datetime import datetime


STEAM_API_URL = "https://store.steampowered.com/api/appdetails?appids={app_id}&cc=us&l=en"
REQUEST_DELAY = 1.5  # seconds between requests to avoid rate limiting


def fetch_app_details(app_id):
    url = STEAM_API_URL.format(app_id=app_id)
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        print(f"  HTTP {e.code} for app {app_id}, skipping", file=sys.stderr)
        return None
    except Exception as e:
        print(f"  Error fetching app {app_id}: {e}", file=sys.stderr)
        return None


def slugify(name):
    slug = name.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def sql_str(value):
    if value is None:
        return "NULL"
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def sql_int(value):
    if value is None:
        return "NULL"
    return str(int(value))


def sql_bool(value):
    if value is None:
        return "FALSE"
    return "TRUE" if value else "FALSE"


def sql_json(value):
    if value is None:
        return "NULL"
    escaped = json.dumps(value, ensure_ascii=False).replace("'", "''")
    return f"'{escaped}'::jsonb"


def generate_steam_key():
    chars = string.ascii_uppercase + string.digits
    segment = lambda: ''.join(random.choices(chars, k=5))
    return f"{segment()}-{segment()}-{segment()}"


def parse_release_date(release_date_obj):
    if not release_date_obj or not release_date_obj.get("date"):
        return "NULL", "NULL"
    raw = release_date_obj["date"]
    for fmt in ("%b %d, %Y", "%d %b, %Y", "%B %d, %Y", "%B %Y", "%b %Y"):
        try:
            parsed = datetime.strptime(raw, fmt)
            return f"'{parsed.strftime('%Y-%m-%d')}'", sql_str(raw)
        except ValueError:
            continue
    return "NULL", sql_str(raw)


def generate_sql(responses):
    lines = []
    lines.append("-- Auto-generated by fetch_and_generate_sql.py")
    lines.append(f"-- Generated at: {datetime.utcnow().isoformat()}Z")
    lines.append("-- Wrapping in a transaction for atomicity")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")

    for app_id_str, result in responses.items():
        if not result or not result.get("success"):
            continue

        d = result["data"]
        app_id = d.get("steam_appid", int(app_id_str))
        name = d.get("name", "")
        slug = slugify(name)

        # Price
        price = d.get("price_overview")
        currency = price.get("currency") if price else None
        price_initial = price.get("initial") if price else None
        price_final = price.get("final") if price else None
        discount_percent = price.get("discount_percent", 0) if price else 0

        # Skip free games (price 0) and games with no currency
        if d.get("is_free") or price_final == 0 or price_final is None or currency is None:
            continue

        # Platforms
        platforms = d.get("platforms", {})

        # Release date
        release_date, release_date_raw = parse_release_date(d.get("release_date"))

        # Required age
        required_age = d.get("required_age", 0)
        if isinstance(required_age, str):
            required_age = int(required_age) if required_age.isdigit() else 0

        # Metacritic & recommendations
        metacritic = d.get("metacritic", {})
        metacritic_score = metacritic.get("score") if metacritic else None
        recommendations = d.get("recommendations", {})
        recommendations_total = recommendations.get("total", 0) if recommendations else 0

        lines.append(f"-- ── {name} (appid: {app_id}) ──")
        lines.append("")

        # INSERT game
        lines.append(f"""\
INSERT INTO games (
    steam_app_id, name, slug,
    detailed_description, about_the_game, supported_languages,
    header_image, required_age,
    release_date, release_date_raw,
    metacritic_score, recommendations_total,
    platform_windows, platform_mac, platform_linux,
    currency, price_initial, price_final, discount_percent,
    pc_requirements, mac_requirements, linux_requirements,
    reduction_percentage, steam_key
) VALUES (
    {sql_int(app_id)}, {sql_str(name)}, {sql_str(slug)},
    {sql_str(d.get('detailed_description'))}, {sql_str(d.get('about_the_game'))}, {sql_str(d.get('supported_languages'))},
    {sql_str(d.get('header_image'))}, {sql_int(required_age)},
    {release_date}, {release_date_raw},
    {sql_int(metacritic_score)}, {sql_int(recommendations_total)},
    {sql_bool(platforms.get('windows'))}, {sql_bool(platforms.get('mac'))}, {sql_bool(platforms.get('linux'))},
    {sql_str(currency)}, {sql_int(price_initial)}, {sql_int(price_final)}, {sql_int(discount_percent)},
    {sql_json(d.get('pc_requirements'))}, {sql_json(d.get('mac_requirements'))}, {sql_json(d.get('linux_requirements'))},
    {sql_int(random.randint(15, 85))}, {sql_str(generate_steam_key())}
) ON CONFLICT (steam_app_id) DO UPDATE SET
    name = EXCLUDED.name,
    detailed_description = EXCLUDED.detailed_description,
    about_the_game = EXCLUDED.about_the_game,
    supported_languages = EXCLUDED.supported_languages,
    header_image = EXCLUDED.header_image,
    required_age = EXCLUDED.required_age,
    release_date = EXCLUDED.release_date,
    release_date_raw = EXCLUDED.release_date_raw,
    metacritic_score = EXCLUDED.metacritic_score,
    recommendations_total = EXCLUDED.recommendations_total,
    platform_windows = EXCLUDED.platform_windows,
    platform_mac = EXCLUDED.platform_mac,
    platform_linux = EXCLUDED.platform_linux,
    currency = EXCLUDED.currency,
    price_initial = EXCLUDED.price_initial,
    price_final = EXCLUDED.price_final,
    discount_percent = EXCLUDED.discount_percent,
    pc_requirements = EXCLUDED.pc_requirements,
    mac_requirements = EXCLUDED.mac_requirements,
    linux_requirements = EXCLUDED.linux_requirements,
    reduction_percentage = EXCLUDED.reduction_percentage,
    steam_key = EXCLUDED.steam_key;""")
        lines.append("")

        # Developers & publishers
        for dev in d.get("developers", []):
            lines.append(f"INSERT INTO companies (name) VALUES ({sql_str(dev)}) ON CONFLICT (name) DO NOTHING;")
        for pub in d.get("publishers", []):
            lines.append(f"INSERT INTO companies (name) VALUES ({sql_str(pub)}) ON CONFLICT (name) DO NOTHING;")

        if d.get("developers") or d.get("publishers"):
            lines.append("")
            for dev in d.get("developers", []):
                lines.append(
                    f"INSERT INTO game_companies (game_id, company_id, role) "
                    f"SELECT g.id, c.id, 'developer' FROM games g, companies c "
                    f"WHERE g.steam_app_id = {sql_int(app_id)} AND c.name = {sql_str(dev)} "
                    f"ON CONFLICT DO NOTHING;"
                )
            for pub in d.get("publishers", []):
                lines.append(
                    f"INSERT INTO game_companies (game_id, company_id, role) "
                    f"SELECT g.id, c.id, 'publisher' FROM games g, companies c "
                    f"WHERE g.steam_app_id = {sql_int(app_id)} AND c.name = {sql_str(pub)} "
                    f"ON CONFLICT DO NOTHING;"
                )
            lines.append("")

        # Genres
        for genre in d.get("genres", []):
            gid = genre.get("id")
            gdesc = genre.get("description")
            lines.append(
                f"INSERT INTO genres (id, description) VALUES ({sql_int(gid)}, {sql_str(gdesc)}) "
                f"ON CONFLICT (id) DO UPDATE SET description = EXCLUDED.description;"
            )
            lines.append(
                f"INSERT INTO game_genres (game_id, genre_id) "
                f"SELECT g.id, {sql_int(gid)} FROM games g WHERE g.steam_app_id = {sql_int(app_id)} "
                f"ON CONFLICT DO NOTHING;"
            )

        if d.get("genres"):
            lines.append("")

        # Categories
        for cat in d.get("categories", []):
            cid = cat.get("id")
            cdesc = cat.get("description")
            lines.append(
                f"INSERT INTO categories (id, description) VALUES ({sql_int(cid)}, {sql_str(cdesc)}) "
                f"ON CONFLICT (id) DO UPDATE SET description = EXCLUDED.description;"
            )
            lines.append(
                f"INSERT INTO game_categories (game_id, category_id) "
                f"SELECT g.id, {sql_int(cid)} FROM games g WHERE g.steam_app_id = {sql_int(app_id)} "
                f"ON CONFLICT DO NOTHING;"
            )

        if d.get("categories"):
            lines.append("")

        # Screenshots
        for i, ss in enumerate(d.get("screenshots", [])):
            lines.append(
                f"INSERT INTO screenshots (game_id, steam_id, path_thumbnail, path_full, position) "
                f"SELECT g.id, {sql_int(ss.get('id'))}, {sql_str(ss.get('path_thumbnail'))}, "
                f"{sql_str(ss.get('path_full'))}, {sql_int(i)} "
                f"FROM games g WHERE g.steam_app_id = {sql_int(app_id)};"
            )

        if d.get("screenshots"):
            lines.append("")

        # Movies
        for i, mov in enumerate(d.get("movies", [])):
            lines.append(
                f"INSERT INTO movies (game_id, steam_id, name, thumbnail, dash_av1, dash_h264, hls_h264, highlight, position) "
                f"SELECT g.id, {sql_int(mov.get('id'))}, {sql_str(mov.get('name'))}, "
                f"{sql_str(mov.get('thumbnail'))}, {sql_str(mov.get('dash_av1'))}, "
                f"{sql_str(mov.get('dash_h264'))}, {sql_str(mov.get('hls_h264'))}, "
                f"{sql_bool(mov.get('highlight'))}, {sql_int(i)} "
                f"FROM games g WHERE g.steam_app_id = {sql_int(app_id)};"
            )

        if d.get("movies"):
            lines.append("")

        lines.append("")

    lines.append("COMMIT;")
    return "\n".join(lines)


def load_app_ids(path):
    with open(path, "r") as f:
        ids = []
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                ids.append(line)
        return ids


def main():
    if len(sys.argv) < 2:
        print(f"Usage: python {sys.argv[0]} <app_ids.txt> [output.sql]", file=sys.stderr)
        print("  app_ids.txt: one Steam app ID per line", file=sys.stderr)
        print("  output.sql:  defaults to stdout", file=sys.stderr)
        sys.exit(1)

    app_ids = load_app_ids(sys.argv[1])
    print(f"Loaded {len(app_ids)} app IDs", file=sys.stderr)

    responses = {}
    for i, app_id in enumerate(app_ids):
        print(f"[{i + 1}/{len(app_ids)}] Fetching app {app_id}...", file=sys.stderr)
        result = fetch_app_details(app_id)
        if result and str(app_id) in result:
            responses[str(app_id)] = result[str(app_id)]
        else:
            print(f"  No data returned for {app_id}", file=sys.stderr)

        if i < len(app_ids) - 1:
            time.sleep(REQUEST_DELAY)

    print(f"\nSuccessfully fetched {len(responses)} / {len(app_ids)} games", file=sys.stderr)

    sql = generate_sql(responses)

    if len(sys.argv) >= 3:
        with open(sys.argv[2], "w", encoding="utf-8") as f:
            f.write(sql)
        print(f"SQL written to {sys.argv[2]}", file=sys.stderr)
    else:
        print(sql)


if __name__ == "__main__":
    main()
