name: CD Prod — Backend

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Tag to apply to the image (e.g. v1.0.0)"
        required: true

jobs:
  build-push-backend:
    name: Build, push & scan backend
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_docker-build.yaml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fullstack_project/backend
      image-tag: ${{ inputs.image-tag || github.ref_name }}
      also-tag-latest: false
      validate-tag: true
      dockerfile-context: ./backend
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-push-postgres-game:
    name: Build, push & scan postgres-game
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_docker-build.yaml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fullstack_project/postgres-game
      image-tag: ${{ inputs.image-tag || github.ref_name }}
      also-tag-latest: false
      validate-tag: true
      dockerfile-context: .
      dockerfile-path: infra/docker/postgres-game/Dockerfile
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-backend:
    needs: build-push-backend
    uses: ./.github/workflows/_deploy.yaml
    with:
      deployment-name: backend-svc
      container-name: condensation-backend
      namespace: prod
      image: ghcr.io/${{ github.repository_owner }}/fullstack_project/backend:${{ inputs.image-tag || github.ref_name }}
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_USER: ${{ secrets.VPS_USER }}

  deploy-postgres-game:
    needs: build-push-postgres-game
    uses: ./.github/workflows/_deploy.yaml
    with:
      deployment-name: postgres-game
      container-name: postgres-game
      namespace: prod
      image: ghcr.io/${{ github.repository_owner }}/fullstack_project/postgres-game:${{ inputs.image-tag || github.ref_name }}
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_USER: ${{ secrets.VPS_USER }}
