name: CD Dev — Frontend

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-push-scan:
    name: Build, push & scan
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_docker-build.yaml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fullstack_project/frontend
      image-tag: dev
      dockerfile-context: ./frontend
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build-push-scan
    uses: ./.github/workflows/_deploy.yaml
    with:
      deployment-name: frontend-svc
      namespace: dev
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_USER: ${{ secrets.VPS_USER }}
