name: CD Dev — Shipping Service

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-push-scan:
    name: Build, push & scan
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_docker-build.yaml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fullstack_project/shipping
      image-tag: dev
      dockerfile-context: ./backend/shipping-service
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
